

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd
import statistics

### Step 2. Import the dataset Euro_2012_stats_TEAM

### Step 3. Assign it to a variable called euro12.

In [2]:
euro12=pd.read_csv("Euro_2012_stats_TEAM.csv")

### Step 4. Select only the Goal column.

In [3]:
euro12['Goals']

0      4.0
1      4.0
2      4.0
3      5.0
4      3.0
5     10.0
6      5.0
7      6.0
8      2.0
9      2.0
10     6.0
11     1.0
12     5.0
13    12.0
14     5.0
15     2.0
16     NaN
17     NaN
18     NaN
19     NaN
Name: Goals, dtype: float64

### Step 5. How many team participated in the Euro2012?

In [7]:
team=euro12['Team'].shape
#len(team)
team

(20,)

### Step 6. What is the number of columns in the dataset?

In [36]:
len(euro12.columns)

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [9]:
selection=euro12.loc[:,['Team','Yellow Cards','Red Cards']]
discipline=pd.DataFrame(selection)
discipline

                                                 Team  Yellow Cards  Red Cards
0                                             Croatia           9.0        0.0
1                                      Czech Republic           7.0        0.0
2                                             Denmark           4.0        0.0
3                                             England           5.0        0.0
4                                              France           6.0        0.0
5                                             Germany           4.0        0.0
6                                              Greece           9.0        1.0
7                                               Italy          16.0        0.0
8                                         Netherlands           5.0        0.0
9                                              Poland           7.0        1.0
10                                           Portugal          12.0        0.0
11                                Republic of Ireland           6.0        1.0
12                                             Russia           6.0        0.0
13                                              Spain          11.0        0.0
14                                             Sweden           7.0        0.0
15                                            Ukraine           5.0        0.0
16                                                NaN           NaN        NaN
17                                                NaN           NaN        NaN
18                                                NaN           NaN        NaN
19  https://towardsdatascience.com/data-handling-u...           NaN        NaN

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [5]:
inp=input('1 for Red Color or 0')

sel_col=euro12.loc[:,'Team']
d_frame=pd.DataFrame(sel_col)

sets= euro12['Red Cards'] == int(inp)

d_frame[sets]

1 for Red Color or 00

              Team
0          Croatia
1   Czech Republic
2          Denmark
3          England
4           France
5          Germany
7            Italy
8      Netherlands
10        Portugal
12          Russia
13           Spain
14          Sweden
15         Ukraine

In [23]:
inp_y=input('Yellow cards: ')
sets= euro12['Yellow Cards'] == int(inp_y)

d_frame[sets]

Yellow cards: 0

Empty DataFrame
Columns: [Team, Yellow Cards, Red Cards]
Index: []

### Step 9. Calculate the mean Yellow Cards given per Team

In [10]:
#d_frame['mean']=euro12['Red Cards'].mean()
#d_frame
means=[]
for files in euro12['Yellow Cards']:
    
    means.append(files)
    
    
means

statistics.mean(means)

7.4375

In [129]:
#['Yellow Cards'].mean()
euro12.loc[:,['Team','Yellow Cards']].mean()

Yellow Cards    7.4375
dtype: float64

### Step 10. Filter teams that scored more than 6 goals

In [132]:
sets= euro12['Goals'] > 6

d_frame[sets]

       Team
5   Germany
13    Spain

### Step 11. Select the teams that start with G

In [53]:
sel_col=euro12.loc[:,'Team']
d_frame=pd.DataFrame(sel_col)
ss=euro12['Team']
#sets= s[0] == 'G'
search='G'
s=d_frame['Team'].str.startswith(search)

#ss[s]
#d_frame[sets]

### Step 12. Select the first 7 columns

In [54]:
euro12.head(7)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4.0,13.0,12.0,51.90%,16.00%,32.0,0.0,0.0,0.0,...,13.0,81.30%,41.0,62.0,2.0,9.0,0.0,9.0,9.0,16.0
1,Czech Republic,4.0,13.0,18.0,41.90%,12.90%,39.0,0.0,0.0,0.0,...,9.0,60.10%,53.0,73.0,8.0,7.0,0.0,11.0,11.0,19.0
2,Denmark,4.0,10.0,10.0,50.00%,20.00%,27.0,1.0,0.0,0.0,...,10.0,66.70%,25.0,38.0,8.0,4.0,0.0,7.0,7.0,15.0
3,England,5.0,11.0,18.0,50.00%,17.20%,40.0,0.0,0.0,0.0,...,22.0,88.10%,43.0,45.0,6.0,5.0,0.0,11.0,11.0,16.0
4,France,3.0,22.0,24.0,37.90%,6.50%,65.0,1.0,0.0,0.0,...,6.0,54.60%,36.0,51.0,5.0,6.0,0.0,11.0,11.0,19.0
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0,2.0,1.0,0.0,...,10.0,62.60%,63.0,49.0,12.0,4.0,0.0,15.0,15.0,17.0
6,Greece,5.0,8.0,18.0,30.70%,19.20%,32.0,1.0,1.0,1.0,...,13.0,65.10%,67.0,48.0,12.0,9.0,1.0,12.0,12.0,20.0

### Step 13. Select all columns except the last 3.

In [77]:
euro12.iloc[:-3]

#euro12.iloc[:].tail(3)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4.0,13.0,12.0,51.90%,16.00%,32.0,0.0,0.0,0.0,...,13.0,81.30%,41.0,62.0,2.0,9.0,0.0,9.0,9.0,16.0
1,Czech Republic,4.0,13.0,18.0,41.90%,12.90%,39.0,0.0,0.0,0.0,...,9.0,60.10%,53.0,73.0,8.0,7.0,0.0,11.0,11.0,19.0
2,Denmark,4.0,10.0,10.0,50.00%,20.00%,27.0,1.0,0.0,0.0,...,10.0,66.70%,25.0,38.0,8.0,4.0,0.0,7.0,7.0,15.0
3,England,5.0,11.0,18.0,50.00%,17.20%,40.0,0.0,0.0,0.0,...,22.0,88.10%,43.0,45.0,6.0,5.0,0.0,11.0,11.0,16.0
4,France,3.0,22.0,24.0,37.90%,6.50%,65.0,1.0,0.0,0.0,...,6.0,54.60%,36.0,51.0,5.0,6.0,0.0,11.0,11.0,19.0
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0,2.0,1.0,0.0,...,10.0,62.60%,63.0,49.0,12.0,4.0,0.0,15.0,15.0,17.0
6,Greece,5.0,8.0,18.0,30.70%,19.20%,32.0,1.0,1.0,1.0,...,13.0,65.10%,67.0,48.0,12.0,9.0,1.0,12.0,12.0,20.0
7,Italy,6.0,34.0,45.0,43.00%,7.50%,110.0,2.0,0.0,0.0,...,20.0,74.10%,101.0,89.0,16.0,16.0,0.0,18.0,18.0,19.0
8,Netherlands,2.0,12.0,36.0,25.00%,4.10%,60.0,2.0,0.0,0.0,...,12.0,70.60%,35.0,30.0,3.0,5.0,0.0,7.0,7.0,15.0
9,Poland,2.0,15.0,23.0,39.40%,5.20%,48.0,0.0,0.0,0.0,...,6.0,66.70%,48.0,56.0,3.0,7.0,1.0,7.0,7.0,17.0
10,Portugal,6.0,22.0,42.0,34.30%,9.30%,82.0,6.0,0.0,0.0,...,10.0,71.50%,73.0,90.0,10.0,12.0,0.0,14.0,14.0,16.0
11,Republic of Ireland,1.0,7.0,12.0,36.80%,5.20%,28.0,0.0,0.0,0.0,...,17.0,65.40%,43.0,51.0,11.0,6.0,1.0,10.0,10.0,17.0
12,Russia,5.0,9.0,31.0,22.50%,12.50%,59.0,2.0,0.0,0.0,...,10.0,77.00%,34.0,43.0,4.0,6.0,0.0,7.0,7.0,16.0
13,Spain,12.0,42.0,33.0,55.90%,16.00%,100.0,0.0,1.0,0.0,...,15.0,93.80%,102.0,83.0,19.0,11.0,0.0,17.0,17.0,18.0
14,Sweden,5.0,17.0,19.0,47.20%,13.80%,39.0,3.0,0.0,0.0,...,8.0,61.60%,35.0,51.0,7.0,7.0,0.0,9.0,9.0,18.0
15,Ukraine,2.0,7.0,26.0,21.20%,6.00%,38.0,0.0,0.0,0.0,...,13.0,76.50%,48.0,31.0,4.0,5.0,0.0,9.0,9.0,18.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [35]:
#euro12.loc['Team']
euro12.loc[[3,7,12],['Team','Shooting Accuracy']]

       Team Shooting Accuracy
3   England            50.00%
7     Italy            43.00%
12   Russia            22.50%

### Step 15. Use apply method on Goal Column to make a new column called Performance, using following conditions

1. If Goals are less than or equal to 2, peformance is **Below Avg**
2. If Goals are more than 2 and less than or equal to 5, peformance is **Average**
3. If Goals are more than 5 and less than or equal to 10, peformance is **Above Average**
4. If Goals are more than 10 then peformance is **Excellent**

In [55]:
euro12['Performance']=='1'
for a in euro12.Goals:
    if a <= 2:
        f=lambda x: euro12['Performance']='Below Avg'
        
#    elif a>2 && a<=5:
#        lambda x: euro12['Performance']=='Average'
#    elif a>5 && a<=10:
#        lambda x: euro12['Performance']=='Above Average'
    elif a>10:
        f=lambda x:euro12['Performance']='Excellent' 
        
        #euro12['Performance']==
    df=euro12.apply(f)
obj= euro12.apply()

SyntaxError: can't assign to lambda (<ipython-input-55-b048fea44650>, line 11)

In [84]:
df=pd.DataFrame(euro12)
lists=[]
lists = df['Goals']
for a in lists:
    if a <= 2:
        s=df['Performance']='Below Avg'
        sets=df['Performance']
    elif a>2 and a<=5:
        df['Performance']='Average'
        sets=df['Performance']
    elif a>5 and a<=10:
        df['Performance']='Above Average'
        sets=df['Performance']
    elif a>10:
        df['Performance']='Excellent'
        sets=df['Performance']
    
sets

0     Below Avg
1     Below Avg
2     Below Avg
3     Below Avg
4     Below Avg
5     Below Avg
6     Below Avg
7     Below Avg
8     Below Avg
9     Below Avg
10    Below Avg
11    Below Avg
12    Below Avg
13    Below Avg
14    Below Avg
15    Below Avg
16    Below Avg
17    Below Avg
18    Below Avg
19    Below Avg
Name: Performance, dtype: object